## python libraries for data science
** data science

## introduction to numpy
* the learning objects  of this section are:
* understand advantages of vectorized code using numpy(over standardpython ways)
* create numpy arrays 
* convert list and tuples to  numpy arrays
* create(initialize)arrays
* inspect the structure and content of arrays
* subsets,slice,index,and iterate through arrays
* compare computations times in numpy and satndard python lists

In [1]:
import numpy as np

In [3]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [8]:
ar2=np.array([[1,2,3],[4,5,6]])
print(ar2)
print(type(ar2))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [11]:
ar3=np.array([[1,2,3],[4,5,6],[7,8,9]])
ar3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
l=np.array([1,2,3,4])
l**2

array([ 1,  4,  9, 16], dtype=int32)

In [12]:
s=np.array([4,5,6,7])
l+s

array([ 5,  7,  9, 11])

In [13]:
l[1]

2

In [14]:
l[2]

3

In [19]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
a1=np.arange(1,10,3)
a1

array([1, 4, 7])

In [23]:
a2=np.linspace(1,2,10)
a2

array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
       1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

In [24]:
ran(1,5,10)

NameError: name 'ran' is not defined

In [25]:
ar2.reshape(2,-1)
ar2

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
ar3.reshape(-1,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
ar2.reshape(2,-1)
ar2

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
ar2.reshape(-1,3)
ar2

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
ar3.reshape(2,1)

ValueError: cannot reshape array of size 9 into shape (2,1)

In [31]:
a.itemsize

4

In [32]:
a.ndim

1

In [34]:
a.shape

(3,)

In [35]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_arg',
 '

In [36]:
help(np.shape)

Help on function shape in module numpy:

shape(a)
    Return the shape of an array.
    
    Parameters
    ----------
    a : array_like
        Input array.
    
    Returns
    -------
    shape : tuple of ints
        The elements of the shape tuple give the lengths of the
        corresponding array dimensions.
    
    See Also
    --------
    alen
    ndarray.shape : Equivalent array method.
    
    Examples
    --------
    >>> np.shape(np.eye(3))
    (3, 3)
    >>> np.shape([[1, 2]])
    (1, 2)
    >>> np.shape([0])
    (1,)
    >>> np.shape(0)
    ()
    
    >>> a = np.array([(1, 2), (3, 4)], dtype=[('x', 'i4'), ('y', 'i4')])
    >>> np.shape(a)
    (2,)
    >>> a.shape
    (2,)



In [38]:
d=np.arange(1,500,10)
d

array([  1,  11,  21,  31,  41,  51,  61,  71,  81,  91, 101, 111, 121,
       131, 141, 151, 161, 171, 181, 191, 201, 211, 221, 231, 241, 251,
       261, 271, 281, 291, 301, 311, 321, 331, 341, 351, 361, 371, 381,
       391, 401, 411, 421, 431, 441, 451, 461, 471, 481, 491])

In [39]:
d[49]#0-49

491

In [42]:
np.ones((1,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [43]:
np.ones((1,10),dtype=int)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [45]:
np.zeros((2,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

In [46]:
np.eye(10,10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [47]:
ar2

array([[1, 2, 3],
       [4, 5, 6]])

In [49]:
a2.T

array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
       1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

In [50]:
np.transpose(ar2)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [53]:
np.random.random((2,10))

array([[0.43514863, 0.09540967, 0.8941628 , 0.88908734, 0.67543358,
        0.98566913, 0.1434106 , 0.36940789, 0.05675866, 0.93362546],
       [0.10794164, 0.30001507, 0.0686851 , 0.24963395, 0.90198549,
        0.42474692, 0.5655627 , 0.20154998, 0.27931071, 0.78967677]])

In [56]:
f=np.random.randint(1,200,(25,6))
f

array([[ 22,  65, 161, 158, 144,  54],
       [ 68,  20,  97,  19,  46, 159],
       [199, 138,  40, 107, 157, 178],
       [ 75,  57,  86,  51,  37, 185],
       [130,  93, 178, 197, 134, 100],
       [ 35,  14, 160, 189, 191,  83],
       [ 42, 142, 121, 138,   1, 147],
       [104,  49,  42,  12,  32, 115],
       [116, 199,  71, 118,  59,  81],
       [ 59,  71,  63,  25, 192,  89],
       [ 44, 165, 115,  95, 186, 108],
       [ 28,  31, 116,  39,  79,  57],
       [188,  86,  25,  44, 142, 191],
       [ 93, 107, 162, 113,  55,  20],
       [ 75,  52,   5, 137, 146, 157],
       [143, 118,  22, 114, 170, 150],
       [195,  31,  59, 179, 167, 179],
       [132, 127,  24, 169,  83, 144],
       [110,  30,  99,  22, 180, 145],
       [ 10, 148,  48,  33, 178, 155],
       [165,  96,  60,  18,  33, 186],
       [ 38,  37,  34, 146,  73, 179],
       [187,  93,  19, 154, 132,  82],
       [146,  66, 125, 161, 133,  40],
       [ 99, 185,  65,  50, 144,   2]])

In [57]:
f.shape

(25, 6)

In [58]:
f[1:5:2]

array([[ 68,  20,  97,  19,  46, 159],
       [ 75,  57,  86,  51,  37, 185]])

In [59]:
f[[2,3,4],[2,3,4]]

array([ 40,  51, 134])

In [60]:
f[2,[2,4]]

array([ 40, 157])

In [61]:
np.sqrt(ar2)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [62]:
np.exp(ar2)

array([[  2.71828183,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [63]:
np.sin(ar2)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ]])

In [64]:
a2

array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
       1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

In [65]:
a

array([1, 4, 7])

In [66]:
np.log(ar2)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947]])

In [68]:
np.full((1,3),10)

array([[10, 10, 10]])

In [71]:
s=np.array([[1,2],[4,5],[7,8],[9,10]])
s

array([[ 1,  2],
       [ 4,  5],
       [ 7,  8],
       [ 9, 10]])

In [73]:
s.flatten()

array([ 1,  2,  4,  5,  7,  8,  9, 10])

In [75]:
np.tile(s,2)

array([[ 1,  2,  1,  2],
       [ 4,  5,  4,  5],
       [ 7,  8,  7,  8],
       [ 9, 10,  9, 10]])

In [76]:
s

array([[ 1,  2],
       [ 4,  5],
       [ 7,  8],
       [ 9, 10]])

In [77]:
np.resize(1,2)

array([1, 1])

In [78]:
import math

In [79]:
math.pi

3.141592653589793

In [80]:
math.pow(2,3)

8.0